@echo off
Title YTM build
echo Installing components...
call npm install
echo Translating typescript into javascript...
call npm run translate
echo Executing npm build-script...
call npm run build
pause
